const q=(question,options,answer,explain)=>({question,options,answer,explain});
window.quizData={
  1:[q("Sản xuất bồi đắp tạo vật thể bằng cách nào?",["Thêm vật liệu theo lớp","Cắt bỏ vật liệu","Đổ khuôn duy nhất","Uốn tấm kim loại"],0,"In 3D FDM đặt vật liệu theo nhiều lớp."),q("Bước nào diễn ra trước slicing?",["Xuất mô hình","In sản phẩm","Tháo support","Sơn sản phẩm"],0,"Cần có tệp mô hình trước khi cắt lớp."),q("In 3D luôn rẻ nhất khi sản xuất hàng triệu sản phẩm.",["Đúng","Sai"],1,"Sản xuất hàng loạt thường phù hợp hơn với phương pháp khác."),q("Ưu thế nổi bật của in 3D?",["Cá nhân hóa và tạo mẫu nhanh","Không bao giờ lỗi","Không cần thiết kế","In mọi vật liệu"],0,"Cá nhân hóa và tạo mẫu là điểm mạnh."),q("Máy in tạo lớp kế tiếp dựa trên gì?",["Đường chạy từ phần mềm cắt lớp","Màu màn hình","Tên file","Kích thước bàn"],0,"Slicer tạo đường chạy theo từng lớp.")],
  2:[q("Trục biểu diễn chiều cao thường là?",["X","Y","Z","W"],2,"Z thường là phương thẳng đứng."),q("Đơn vị mặc định phổ biến trong Tinkercad?",["mm","m","inch","px"],0,"Thiết kế in 3D thường dùng milimét."),q("Đổi góc nhìn có đổi kích thước vật thể không?",["Có","Không"],1,"Góc nhìn chỉ đổi cách quan sát."),q("Khối nào phù hợp làm bánh xe?",["Cylinder","Wedge","Box","Cone"],0,"Cylinder là điểm khởi đầu hợp lý."),q("Phân rã vật thể giúp gì?",["Nhận ra các khối đơn giản","Tăng nhiệt nozzle","Tạo G-code","Xóa file"],0,"Ta xây vật phức tạp từ khối cơ bản.")],
  3:[q("Workplane dùng để?",["Đặt hình","Xuất STL","In ngay","Chấm quiz"],0,"Đó là bề mặt làm việc."),q("ViewCube giúp?",["Đổi góc nhìn","Group","Khoét lỗ","Đổi vật liệu"],0,"ViewCube điều hướng góc nhìn."),q("Công cụ nào hoàn tác?",["Undo","Delete","Mirror","Align"],0,"Undo quay lại thao tác trước."),q("Shapes panel chứa gì?",["Các hình khối","Điểm quiz","G-code","Video"],0,"Bạn kéo shape vào workplane."),q("Đặt tên thiết kế có ích?",["Dễ tìm và nộp đúng","Làm máy in nhanh hơn","Tăng infill","Thay nozzle"],0,"Tên rõ ràng giúp quản lý file.")],
  4:[q("Muốn nâng vật lên khỏi workplane, đổi trục?",["Z","X","Y","Không trục nào"],0,"Nâng/hạ là chuyển động theo Z."),q("Scale đồng đều nghĩa là?",["Giữ tỉ lệ các chiều","Chỉ đổi X","Chỉ xoay","Tạo lỗ"],0,"Các chiều thay đổi cùng tỉ lệ."),q("Duplicate dùng để?",["Nhân bản","Căn giữa","Khoét lỗ","Xuất file"],0,"Duplicate tạo bản sao."),q("Nhập số tốt hơn kéo mắt khi cần?",["Kích thước chính xác","Màu đẹp","Nhiều layer","Video"],0,"Số đo giúp kiểm soát chính xác."),q("Multiselect cho phép?",["Chọn nhiều vật","In nhiều máy","Mở nhiều web","Lưu nhiều tên"],0,"Chọn nhiều khối để thao tác cùng lúc.")],
  5:[q("Hole chỉ khoét khi nào?",["Giao Solid và Group","Đứng riêng","Đổi màu","Chưa chọn"],0,"Hole loại phần giao sau Group."),q("Align dùng để?",["Căn vị trí","Đổi nhiệt","Cắt lớp","Tải PDF"],0,"Align căn tâm hoặc mép."),q("Hai khối không giao nhau thì Hole?",["Không tạo lỗ trên Solid","Xóa toàn bộ","Tự dịch chuyển","Tạo support"],0,"Không có vùng giao để loại bỏ."),q("Ungroup để?",["Tách nhóm","Thêm infill","Đổi trục","Xuất PNG"],0,"Ungroup đưa nhóm về thành phần."),q("Chữ khắc chìm thường dùng?",["Text dạng Hole","Text Solid nổi","Mirror","Ruler"],0,"Text Hole khoét chữ vào nền.")],
  6:[q("Mirror tạo?",["Bản đối xứng","Lỗ","G-code","Quiz"],0,"Mirror lật theo trục."),q("Ruler giúp đọc?",["Vị trí và kích thước","Nhiệt độ phòng","Điểm quiz","Tên lớp"],0,"Ruler phục vụ đo chính xác."),q("Smart Duplicate lặp lại?",["Biến đổi gần nhất","Cả khóa học","Video","File PDF"],0,"Nó lặp phép dịch chuyển/xoay."),q("Workplane tạm hữu ích khi?",["Đặt vật lên bề mặt","Chấm điểm","Đổi theme","Xóa dữ liệu"],0,"Nó tạo bề mặt đặt hình mới."),q("Chọn sai trục Mirror có thể?",["Lật sai hướng","Tăng nhiệt","Mất mạng","Đổi layer"],0,"Luôn kiểm tra hướng trục.")],
  7:[q("Mô hình in tốt cần các bộ phận?",["Thực sự kết nối","Chỉ chạm trên màn hình","Khác màu","Ẩn"],0,"Các thể tích cần nối hợp lệ."),q("Cách thường giảm support?",["Đổi hướng đặt","Tăng tên file","Đổi theme","Thêm quiz"],0,"Orientation ảnh hưởng vùng overhang."),q("Dung sai cố định cho mọi máy?",["Đúng","Sai"],1,"Nó phụ thuộc máy, vật liệu và profile."),q("Đáy phẳng giúp?",["Tăng tiếp xúc bàn in","Tăng điểm quiz","Đổi màu","Xuất nhanh"],0,"Tiếp xúc tốt hỗ trợ bám bàn."),q("Thành quá mỏng có nguy cơ?",["Không in rõ hoặc yếu","Tự dày lên","Luôn đẹp","Không ảnh hưởng"],0,"Giới hạn phụ thuộc quy trình in.")],
  8:[q("Bộ phận làm nóng filament?",["Hotend","Build plate","Khung","ViewCube"],0,"Hotend làm nóng trước nozzle."),q("Bộ phận đẩy filament?",["Extruder","Nozzle","Quạt","Khung"],0,"Extruder cấp vật liệu."),q("Nozzle làm gì?",["Đưa nhựa nóng chảy ra","Đỡ cuộn nhựa","Lưu file","Chấm điểm"],0,"Nozzle tạo đường vật liệu."),q("Build plate có vai trò?",["Đỡ và bám lớp đầu","Tạo STL","Quay camera","Lưu quiz"],0,"Sản phẩm hình thành trên bàn in."),q("G-code được đọc bởi?",["Bộ điều khiển máy","Móc khóa","Filament","Ruler"],0,"Bộ điều khiển biến lệnh thành chuyển động.")],
  9:[q("STL chủ yếu mô tả?",["Bề mặt hình học","Nhiệt độ","Tên học sinh","Điểm quiz"],0,"STL chứa lưới bề mặt."),q("Slicer tạo ra?",["G-code","Ảnh chân dung","Tài khoản","Mật khẩu"],0,"Slicer tạo lệnh máy."),q("Preview trước in để?",["Kiểm tra đường chạy và lỗi","Làm file nặng","Đổi tên lớp","Tắt quạt"],0,"Preview giúp phát hiện vấn đề."),q("Bước sau TEST?",["IMPROVE","ASK","EXPORT","SLICE"],0,"Thiết kế là chu trình cải tiến."),q("Trước export nên kiểm tra?",["Kích thước và mô hình","Điểm mạng","Màu trình duyệt","Ngày sinh"],0,"Kiểm tra trước giúp tránh lãng phí.")],
  10:[q("Layer height thấp thường?",["Mịn hơn, lâu hơn","Thô hơn, nhanh hơn luôn","Không đổi","Xóa support"],0,"Nhiều lớp hơn tăng thời gian."),q("Infill là?",["Cấu trúc bên trong","Vỏ ngoài","Tên file","Bàn in"],0,"Infill hỗ trợ bên trong."),q("Brim thường giúp?",["Bám bàn","Đổi màu","Khoét lỗ","Tạo tài khoản"],0,"Brim tăng diện tích tiếp xúc."),q("Support dùng khi?",["Vùng nhô khó tự đỡ","Tên dài","Quiz khó","Màn hình tối"],0,"Support nâng đỡ overhang."),q("Profile tốt nhất cho mọi mô hình?",["Không","Có"],0,"Cần cân bằng theo mục tiêu.")],
  11:[q("Có nên chạm nozzle vừa in xong?",["Không","Có"],0,"Nozzle có thể gây bỏng."),q("Khi máy bất thường, bước đầu?",["Dừng an toàn và báo giáo viên","Thò tay vào","Tháo máy","Tăng nhiệt"],0,"Ưu tiên an toàn."),q("Warping là?",["Góc cong khỏi bàn","Kéo sợi","Lệch trục màn hình","Mất file"],0,"Bám bàn và co ngót liên quan warping."),q("Nên thay bao nhiêu biến mỗi lần chẩn đoán?",["Một biến có kiểm soát","Tất cả","Không ghi lại","Ngẫu nhiên"],0,"Một thay đổi giúp biết nguyên nhân."),q("Tóc dài khi gần máy?",["Buộc gọn","Để tự do"],0,"Tránh mắc vào bộ phận chuyển động.")],
  12:[q("Thiết kế tốt bắt đầu từ?",["Nhu cầu người dùng","Một shape ngẫu nhiên","Màu yêu thích","Máy in nhanh"],0,"Vấn đề và người dùng định hướng giải pháp."),q("Tiêu chí tốt nên?",["Đo/kiểm tra được","Mơ hồ","Không liên quan","Không thể thử"],0,"Tiêu chí dùng để đánh giá mẫu."),q("Prototype là?",["Mẫu để thử","Sản phẩm không đổi","Tên bài","Mật khẩu"],0,"Mẫu thử giúp học nhanh."),q("Iteration nghĩa là?",["Lặp cải tiến","Xóa mọi thứ","In không thử","Chỉ phác thảo"],0,"Thiết kế tiến bộ qua vòng lặp."),q("Sau khi test nên?",["Ghi phản hồi và cải tiến","Bỏ qua kết quả","Luôn nộp ngay","Đổi người dùng"],0,"Dữ liệu thử nghiệm dẫn đến cải tiến.")]
};
